version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ask_others
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  web:
    env_file:
      - .env
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=ask_others
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    depends_on:
      - db
#    entrypoint: ['sh', 'entrypoint.sh']
