# Generated by Django 4.1 on 2022-09-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_others_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_link',
            field=models.TextField(blank=True),
        ),
    ]
