# Generated by Django 4.1 on 2022-09-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_others_app', '0002_alter_user_avatar_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='./static/attachments'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_link',
            field=models.ImageField(blank=True, null=True, upload_to='./static/avatars'),
        ),
    ]
